### ISSUE TITLE
License query?

### ISSUE THREAD

**Issue by fbyrne** [getsentry/statsdproxy#36]
Hi, 

I was investigating using this proxy for an older application that cannot send tags via statsd.  

What is the current license and is it used in production anywhere currently?

Thank you
Fergus

**Comment by untitaker** [comment]
we haven't rolled this out anywhere, license is Apache-2.0 as per Cargo.toml. will keep this open to fix metadata if/when we polish the project

**Comment by untitaker** [comment]
The license is Apache-2.0. If there are concerns with either the license or the way we publish metadata feel free to open a new issue.
